services:
  nginx:
    image: frontend
    ports:
      - "5173:5173"
    networks:
      - ebuy-network
    depends_on:
      - backend

  backend:
    image: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - ebuy-network

networks:
  ebuy-network:
    driver: bridge