spring.profiles.active=dev
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=f9f057f3954707
spring.mail.password=6bc3aa93753bba
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

api.security.token.accessExpirationHours=2 
api.security.token.refreshExpirationDays=7 

mercadopago.access.token=${MERCADO_PAGO_A_TOKEN}

melhorenvio.api.url=${MELHOR_ENVIO_URL}
melhorenvio.api.token=${MELHOR_ENVIO_TOKEN}
postalcode.cep.default=09930220

azure.blob.storage.url=${AZURE_BLOB_STORAGE_URL}
azure.blob.storage.token.sas=${AZURE_BLOB_STORAGE_TOKEN_SAS}