spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

api.security.token.secret=${JWT_SECRET:my-secret-key}

server.error.include-message=always
server.error.include-binding-errors=always

spring.application.name=auth

spring.jpa.show-sql=false

mercaddo.pago.env=PROD

#mercadopago.access.token=APP_USR-5361035748893016-102700-12b41e09d6e5e189c58d562d4e17108f-1676178659
