-- Tabela categoria com códigos de cor aleatórios
INSERT INTO categoria (nome_categoria, data_hora_cadastro, data_hora_atualizacao, codigo_cor)
VALUES ('Materiais de Escritório', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Festas e Eventos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Artesanato', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33FF'),
       ('Produtos Personalizados', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Brindes Corporativos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Acessórios para Festas', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Festas Temáticas', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF3368'),
       ('Decoração de Interiores', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Decoração de Natal', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Bolsas e Acessórios', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Jogos e Brinquedos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Artigos para Casamento', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Flores e Arranjos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Produtos Ecológicos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Moda e Vestuário', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Bijuterias e Acessórios', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Cosméticos e Beleza', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Equipamentos de Festa', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Alimentos e Bebidas', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Livros e Materiais Didáticos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Tecnologia e Gadgets', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Esportes e Atividades ao Ar Livre', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Saúde e Bem-Estar', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Fotografia e Vídeo', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Gadgets de Cozinha', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Brinquedos Educativos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Materiais para Scrapbook', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Arte e Pintura', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Produtos para Animais de Estimação', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Ferramentas e Materiais de Construção', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Moda Infantil', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Roupas de Bebê', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Artigos para o Dia das Mães', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Artigos para o Dia dos Pais', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Artigos para o Dia das Crianças', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Equipamentos Esportivos', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Roupas de Inverno', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Roupas de Verão', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Equipamentos de Camping', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Arte Digital', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Instrumentos Musicais', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Artigos para Academia', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Decoração para Festas de Aniversário', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Artigos para Festivais', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Presentes para Todas as Ocasiões', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Suprimentos para Escritório', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Artigos de Papelaria', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Equipamentos de Segurança', DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33');

-- Tabela subcategoria com códigos de cor aleatórios
INSERT INTO subcategoria (nome_subcategoria, descricao_subcategoria, fk_categoria, data_hora_cadastro,
                          data_hora_atualizacao, codigo_cor)
VALUES ('Canetas e Lápis', 'Canetas e lápis de diversas cores e tipos', 1, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Papelaria Personalizada', 'Papelaria personalizada para eventos', 1, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Decoração para Festas', 'Itens decorativos para festas e eventos', 2, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33FF'),
       ('Festas Infantis', 'Decoração e artigos para festas infantis', 2, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Artesanato em Papel', 'Materiais para fazer artesanato em papel', 3, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Personalização de Brindes', 'Brindes personalizados para empresas', 4, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Lembrancinhas', 'Lembrancinhas personalizadas para festas', 4, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF3368'),
       ('Camisetas Personalizadas', 'Camisetas com estampas personalizadas', 4, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Brindes para Eventos Corporativos', 'Brindes para eventos e feiras', 5, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Balões Personalizados', 'Balões com mensagens ou imagens', 6, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Decoração de Mesa', 'Artigos para decoração de mesa de festas', 6, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Bandeirinhas e Guirlandas', 'Bandeirinhas e guirlandas para festas', 6, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Toalhas de Mesa', 'Toalhas de mesa personalizadas', 6, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Decoração para Casamento', 'Artigos para decoração de casamentos', 11, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Convites Personalizados', 'Convites feitos sob medida para eventos', 11, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Flores Artificiais', 'Flores artificiais para decoração', 13, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Arranjos Florais', 'Arranjos florais personalizados', 13, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Produtos Sustentáveis', 'Artigos ecológicos e sustentáveis', 14, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Bijuterias Artesanais', 'Bijuterias feitas à mão', 16, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Cosméticos Naturais', 'Produtos de beleza feitos com ingredientes naturais', 17, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Equipamentos de Som', 'Equipamentos para festas e eventos', 18, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Gastronomia para Festas', 'Alimentos e bebidas para festas', 19, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Brinquedos para Bebês', 'Brinquedos educativos e seguros para bebês', 25, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Materiais para Pintura', 'Tintas e pincéis para pintura', 28, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Produtos para Cães', 'Acessórios e brinquedos para cães', 29, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Suprimentos para Jardinagem', 'Ferramentas e materiais para jardinagem', 29, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Roupas para Crianças', 'Roupas e acessórios infantis', 30, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Roupas de Festa', 'Roupas para ocasiões especiais', 30, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Decoração de Natal', 'Itens para decoração natalina', 9, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Artesanato com Madeira', 'Materiais e ferramentas para artesanato em madeira', 3, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Equipamentos de Camping', 'Artigos e equipamentos para camping', 38, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF'),
       ('Instrumentos Musicais para Crianças', 'Instrumentos musicais educativos', 38, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF5733'),
       ('Equipamentos de Yoga', 'Acessórios e equipamentos para yoga', 37, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFBD'),
       ('Flores Naturais', 'Flores frescas para eventos', 13, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF33A8'),
       ('Decoração para Festas de Aniversário', 'Itens para festas de aniversário', 40, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#337BFF'),
       ('Roupas de Verão', 'Roupas leves e confortáveis para o verão', 35, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#B6FF33'),
       ('Artigos de Papelaria para Escritório', 'Suprimentos de papelaria para escritório', 1, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#FF9F33'),
       ('Materiais para Scrapbook', 'Materiais para criação de scrapbook', 28, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FF57'),
       ('Brinquedos para Animais de Estimação', 'Brinquedos e acessórios para pets', 29, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#5733FF'),
       ('Suprimentos para Estudo', 'Materiais escolares e didáticos', 20, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#33FFC4'),
       ('Decoração de Interiores', 'Artigos para decoração de ambientes', 8, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '#338AFF');

INSERT INTO material (nome_material, preco_unitario, estoque, data_hora_cadastro,
                      data_hora_atualizacao )
VALUES
    ('Papel', 0.20, 5, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Cartolina', 0.50, 10, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Tecido', 1.00, 3, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Fita', 0.75, 4, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Plástico', 0.30, 2, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Caneta', 1.50, 20, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Lápis', 0.80, 15, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Caderno', 2.50, 8, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Giz de cera', 0.90, 12, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Borrachas', 0.60, 25, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Marcador permanente', 1.20, 18, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Lápis de cor', 1.10, 22, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Tesoura', 3.00, 7, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Cola', 1.40, 15, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Fita adesiva', 0.90, 11, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Clip', 0.05, 100, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Grampeador', 4.00, 5, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Pasta arquivo', 1.80, 9, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Régua', 0.60, 20, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Caderno brochura', 2.00, 14, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Caderno espiral', 3.50, 10, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Caneta marca-texto', 1.75, 16, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Pincel', 1.00, 8, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Tinta guache', 2.00, 6, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Papel cartão', 0.40, 12, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Corda', 0.25, 30, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Caixa de som', 15.00, 2, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Baterias', 2.50, 20, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Rolo de fita crepe', 1.00, 15, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Capa de chuva', 5.00, 10, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW())),
    ('Protetor auricular', 2.00, 10, DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()));

INSERT INTO produto (nome, preco_venda, descricao, dimensao, desconto, margem_lucro, sku, url_imagem_principal,
                     personalizavel, personalizacao_obrigatoria, fk_categoria, fk_subcategoria, id_img_drive,
                     produto_Ativo, data_hora_cadastro, data_hora_atualizacao)
VALUES
    ('Agenda Minnie', 34.90, 'Agenda decorada com a personagem Minnie.', 'A5', 0.10, 0.50, 'AGENDA-MINNIE',
     'https://ascriativasloja.com.br/wp-content/uploads/2023/01/1-12.jpg', true, true, 1, 1,
     '1OosCxJEq0zdIUuuzpNhzRafG3N6eEyG5', true, NOW(), NOW()),
    ('Agenda Mickey', 34.90, 'Agenda decorada com a personagem Mickey.', 'A5', 0.10, 0.50, 'AGENDA-MICKEY',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh9GrMNq4LrRs6X1Vi4vko2drhPqjBDDwfGVaAaIHiTS2_Dq6TLN96sDZLr4MmBXGYGYg&usqp=CAU',
     true, true, 1, 1, '1bXl8JQW_FQ8i9-OeMcC_2KYss5_3TeWB', true, NOW(), NOW()),
    ('Agenda Stitch', 34.90, 'Agenda decorada com o personagem Stitch.', 'A5', 0.10, 0.50, 'AGENDA-STITCH',
     'https://a-static.mlcdn.com.br/800x560/agenda-diaria-personagem-stitch-para-seu-novo-ano-2021-spiral/pigmamultivendas/10334979371/475381966b4f3da09197b691e1d5f1c5.jpg',
     true, true, 1, 1, '1bJ4H3RLbY8w2I8Gth7_yTVPrbNYgDnv', true, NOW(), NOW()),
    ('Agenda Luffy', 34.90, 'Agenda decorada com o personagem Luffy.', 'A5', 0.10, 0.50, 'AGENDA-LUFFY',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAZsp0YxZ7Z4KzIN5MOA9YteFnKdxJjHwN0w&usqp=CAU',
     true, true, 1, 1, '1MSLIsUToCtiL_YNYVtYbH4HLw7upgl7', true, NOW(), NOW()),
    ('Caderno 10 matérias', 29.90, 'Caderno com 10 matérias.', 'A4', 0.10, 0.50, 'CADERNO-10MATERIAS',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbQnTFmJyd3m8e6XL8HcZdbXcX4UwOpCLAXW&usqp=CAU',
     true, true, 1, 1, '1GQFL5P5nqdrtMYjs5iT9Za9F4_uJwS7', true, NOW(), NOW()),
    ('Caderno 15 matérias', 34.90, 'Caderno com 15 matérias.', 'A4', 0.10, 0.50, 'CADERNO-15MATERIAS',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYxN1SQHhZUDCdojEDgL5hv3cMa4ZZIUnR0g&usqp=CAU',
     true, true, 1, 1, '1PCFlN1s6u5b4-pFnF3uON-1g2XWwhZf', true, NOW(), NOW()),
    ('Caderno 20 matérias', 39.90, 'Caderno com 20 matérias.', 'A4', 0.10, 0.50, 'CADERNO-20MATERIAS',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5mtqCj6lE3EVuv5zY27qJZYN_t0I0uk-9PA&usqp=CAU',
     true, true, 1, 1, '1PYMNYALDbLEZVVl_SFQLx2dpJgOrCl-8', true, NOW(), NOW()),
    ('Caderno 30 matérias', 44.90, 'Caderno com 30 matérias.', 'A4', 0.10, 0.50, 'CADERNO-30MATERIAS',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx0yHRP8Y9tZ4Aauyw4MT5LElC4QayOWRkxA&usqp=CAU',
     true, true, 1, 1, '1sOv2tAjW_oW2_Bk2Wn65VfsqOb0E8a8', true, NOW(), NOW()),
    ('Caneta esferográfica', 2.90, 'Caneta esferográfica azul.', 'Caneta', 0.05, 0.50, 'CANETA-ESFEROGRAFICA',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYmGtvVdRSW-HxXSEH2_sDTxH1QHcOCUe8tQ&usqp=CAU',
     true, true, 1, 1, '1vLQ2aQQsfN6ug1N_luc2h9Uuc3qT5AC', true, NOW(), NOW()),
    ('Caneta hidrográfica', 4.90, 'Caneta hidrográfica com ponta fina.', 'Caneta', 0.05, 0.50, 'CANETA-HIDROGRAFICA',
     'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdG6ZRtKmK9t8EB-_N_8w9oPwDiydMj6FTrA&usqp=CAU',
     true, true, 1, 1, '1myf1ra6gBMe0nJu1sMfthjJ6okmnP-E', true, NOW(), NOW());


INSERT INTO imagens_produto (url_img_adicional, fk_produto, id_img_drive)
VALUES ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 1,
        '1kJUI8FDa3Z4qVDxRvS0wYzeZwGrt55r2'),
       ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 1,
        '1kJUI8FDa3Z4qVDxRvS0wYzeZwGrt55r2'),
       ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 2, 'abc123'),
       ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 3, 'abc123'),
       ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 4, 'abc123'),
       ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 6, 'abc123');

INSERT INTO personalizacao (nome_personalizacao, tipo_personalizacao, fk_produto)
VALUES ('Personalização de Capa', 'Texto', 1),
       ('Personalização de Datas', 'Texto', 2),
       ('Design Especial para Casamento', 'Design', 4),
       ('Mensagem Especial', 'Texto', 3),
       ('Mensagem para Faixa', 'Texto', 6);

INSERT INTO opcao_personalizacao (nome_opcao, descricao, acrescimo_opcao, url_img_opcao, fk_personalizacao,
                                  id_img_drive)
VALUES ('Texto em Ouro', 'Texto na capa em efeito dourado', 5.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 1,
        '1cCAa5y637fsJ4VZ96Lqz5Utz_ZcZKo49'),
       ('Texto em Prata', 'Texto na capa em efeito prateado', 4.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 1,
        '1OLxbmeet0tTxCn5BOIas0LmB7Y4G7pbf'),
       ('Data em Dourado', 'Datas em efeito dourado', 3.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 3, 'abc123'),
       ('Data em Prata', 'Datas em efeito prateado', 2.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 3, 'abc123'),
       ('Design Floral', 'Design floral para casamentos', 8.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 4, 'abc123'),
       ('Design Minimalista', 'Design minimalista para casamentos', 6.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 4,
        'abc123'),
       ('Mensagem em Dourado', 'Mensagem em efeito dourado', 4.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('Mensagem em Prata', 'Mensagem em efeito prateado', 3.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('Mensagem em Vermelho', 'Mensagem em efeito vermelho', 2.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('Mensagem em Azul', 'Mensagem em efeito azul', 2.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('Mensagem em Verde', 'Mensagem em efeito verde', 2.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('Mensagem em Amarelo', 'Mensagem em efeito amarelo', 2.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123'),
       ('Mensagem em Rosa', 'Mensagem em efeito rosa', 2.00,
        'https://drive.google.com/thumbnail?id=1SStxF5xD5SM_HyDM_bk9rD0rY6y8jrOg&sz=w1000', 5, 'abc123');

INSERT INTO material_produto (fk_material, fk_produto, qtd_material_necessario)
VALUES (1, 1, 2),
       (2, 1, 1),
       (1, 2, 3),
       (2, 2, 1),
       (1, 3, 1),
       (2, 3, 1),
       (3, 4, 1),
       (4, 5, 5),
       (1, 6, 2);

INSERT INTO USUARIO
(NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, CARGO_USUARIO, TELEFONE_USUARIO, STATUS_USUARIO, DATA_CADASTRO_USUARIO,
 DATA_ATUALIZACAO_USUARIO, CPF_USUARIO, GENERO_USUARIO, URL_IMG_USUARIO, DATA_NASCIMENTO_USUARIO, ID_GOOGLE)
VALUES ('Cláudio Araújo', 'claudio@gmail.com', '$2b$12$4FM3A0un93R72ieiEddIE.J9hWbrO64j93W4cJZy0jyQcQo2WMFBC', 'ADMIN',
        '(11) 98765-4321', 'HABILITADO',
        DATEADD('DAY', FLOOR(RAND() * 365), NOW()), DATEADD('DAY', FLOOR(RAND() * 365), NOW()), '123.456.789-09', 1,
        'https://drive.google.com/thumbnail?id=14bS2oXh2unEpaM2lgzwpqxPduDYvFsHB&sz=w1000', '2005-01-07', NULL);