INSERT INTO categoria (nome_categoria)
VALUES ('Materiais de Escritório'),
       ('Festas e Eventos'),
       ('Artesanato'),
       ('Produtos Personalizados'),
       ('Brindes Corporativos'),
       ('Acessórios para Festas'),
       ('Festas Temáticas'),
       ('Decoração de Interiores'),
       ('Decoração de Natal'),
       ('Bolsas e Acessórios'),
       ('Jogos e Brinquedos'),
       ('Artigos para Casamento'),
       ('Flores e Arranjos'),
       ('Produtos Ecológicos'),
       ('Moda e Vestuário'),
       ('Bijuterias e Acessórios'),
       ('Cosméticos e Beleza'),
       ('Equipamentos de Festa'),
       ('Alimentos e Bebidas'),
       ('Livros e Materiais Didáticos'),
       ('Tecnologia e Gadgets'),
       ('Esportes e Atividades ao Ar Livre'),
       ('Saúde e Bem-Estar'),
       ('Fotografia e Vídeo'),
       ('Gadgets de Cozinha'),
       ('Brinquedos Educativos'),
       ('Materiais para Scrapbook'),
       ('Arte e Pintura'),
       ('Produtos para Animais de Estimação'),
       ('Ferramentas e Materiais de Construção'),
       ('Moda Infantil'),
       ('Roupas de Bebê'),
       ('Artigos para o Dia das Mães'),
       ('Artigos para o Dia dos Pais'),
       ('Artigos para o Dia das Crianças'),
       ('Equipamentos Esportivos'),
       ('Roupas de Inverno'),
       ('Roupas de Verão'),
       ('Equipamentos de Camping'),
       ('Arte Digital'),
       ('Instrumentos Musicais'),
       ('Artigos para Academia'),
       ('Decoração para Festas de Aniversário'),
       ('Artigos para Festivais'),
       ('Presentes para Todas as Ocasiões'),
       ('Suprimentos para Escritório'),
       ('Artigos de Papelaria'),
       ('Equipamentos de Segurança');


INSERT INTO subcategoria (nome_subcategoria, descricao_subcategoria, fk_categoria)
VALUES ('Canetas e Lápis', 'Canetas e lápis de diversas cores e tipos', 1),
       ('Papelaria Personalizada', 'Papelaria personalizada para eventos', 1),
       ('Decoração para Festas', 'Itens decorativos para festas e eventos', 2),
       ('Festas Infantis', 'Decoração e artigos para festas infantis', 2),
       ('Artesanato em Papel', 'Materiais para fazer artesanato em papel', 3),
       ('Personalização de Brindes', 'Brindes personalizados para empresas', 4),
       ('Lembrancinhas', 'Lembrancinhas personalizadas para festas', 4),
       ('Camisetas Personalizadas', 'Camisetas com estampas personalizadas', 4),
       ('Brindes para Eventos Corporativos', 'Brindes para eventos e feiras', 5),
       ('Balões Personalizados', 'Balões com mensagens ou imagens', 6),
       ('Decoração de Mesa', 'Artigos para decoração de mesa de festas', 6),
       ('Bandeirinhas e Guirlandas', 'Bandeirinhas e guirlandas para festas', 6),
       ('Toalhas de Mesa', 'Toalhas de mesa personalizadas', 6),
       ('Decoração para Casamento', 'Artigos para decoração de casamentos', 11),
       ('Convites Personalizados', 'Convites feitos sob medida para eventos', 11),
       ('Flores Artificiais', 'Flores artificiais para decoração', 13),
       ('Arranjos Florais', 'Arranjos florais personalizados', 13),
       ('Produtos Sustentáveis', 'Artigos ecológicos e sustentáveis', 14),
       ('Bijuterias Artesanais', 'Bijuterias feitas à mão', 16),
       ('Cosméticos Naturais', 'Produtos de beleza feitos com ingredientes naturais', 17),
       ('Equipamentos de Som', 'Equipamentos para festas e eventos', 18),
       ('Gastronomia para Festas', 'Alimentos e bebidas para festas', 19),
       ('Brinquedos para Bebês', 'Brinquedos educativos e seguros para bebês', 25),
       ('Materiais para Pintura', 'Tintas e pincéis para pintura', 28),
       ('Produtos para Cães', 'Acessórios e brinquedos para cães', 29),
       ('Suprimentos para Jardinagem', 'Ferramentas e materiais para jardinagem', 29),
       ('Roupas para Crianças', 'Roupas e acessórios infantis', 30),
       ('Roupas de Festa', 'Roupas para ocasiões especiais', 30),
       ('Decoração de Natal', 'Itens para decoração natalina', 9),
       ('Artesanato com Madeira', 'Materiais e ferramentas para artesanato em madeira', 3),
       ('Equipamentos de Camping', 'Artigos e equipamentos para camping', 38),
       ('Instrumentos Musicais para Crianças', 'Instrumentos musicais educativos', 38),
       ('Equipamentos de Yoga', 'Acessórios e equipamentos para yoga', 37),
       ('Flores Naturais', 'Flores frescas para eventos', 13),
       ('Decoração para Festas de Aniversário', 'Itens para festas de aniversário', 40),
       ('Roupas de Verão', 'Roupas leves e confortáveis para o verão', 35),
       ('Artigos de Papelaria para Escritório', 'Suprimentos de papelaria para escritório', 1),
       ('Materiais para Scrapbook', 'Materiais para criação de scrapbook', 28),
       ('Brinquedos para Animais de Estimação', 'Brinquedos e acessórios para pets', 29),
       ('Suprimentos para Estudo', 'Materiais escolares e didáticos', 20),
       ('Decoração de Interiores', 'Artigos para decoração de ambientes', 8);

INSERT INTO material (id_material, nome_material, preco_unitario, estoque)
VALUES (1, 'Papel', 0.20, 5),
       (2, 'Cartolina', 0.50, 10),
       (3, 'Tecido', 1.00, 3),
       (4, 'Fita', 0.75, 4),
       (5, 'Plástico', 0.30, 2),
       (6, 'Caneta', 1.50, 20),
       (7, 'Lápis', 0.80, 15),
       (8, 'Caderno', 2.50, 8),
       (9, 'Giz de cera', 0.90, 12),
       (10, 'Borrachas', 0.60, 25),
       (11, 'Marcador permanente', 1.20, 18),
       (12, 'Lápis de cor', 1.10, 22),
       (13, 'Tesoura', 3.00, 7),
       (14, 'Cola', 1.40, 15),
       (15, 'Fita adesiva', 0.90, 11),
       (16, 'Clip', 0.05, 100),
       (17, 'Grampeador', 4.00, 5),
       (18, 'Pasta arquivo', 1.80, 9),
       (19, 'Régua', 0.60, 20),
       (20, 'Caderno brochura', 2.00, 14),
       (21, 'Caderno espiral', 3.50, 10),
       (22, 'Caneta marca-texto', 1.75, 16),
       (23, 'Pincel', 1.00, 8),
       (24, 'Tinta guache', 2.00, 6),
       (25, 'Papel cartão', 0.40, 12),
       (26, 'Corda', 0.25, 30),
       (27, 'Caixa de som', 15.00, 2),
       (28, 'Baterias', 2.50, 20),
       (29, 'Rolo de fita crepe', 1.00, 15),
       (30, 'Capa de chuva', 5.00, 10),
       (31, 'Protetor auricular', 2.00, 10);

INSERT INTO produto (nome, preco_venda, descricao, dimensao, desconto, margem_lucro, sku, url_imagem_principal,
                     personalizavel, personalizacao_obrigatoria, fk_categoria, fk_subcategoria, id_img_drive)
VALUES ('Caderno Personalizado', 29.90, 'Caderno com capa personalizada e folhas pautadas.', 'A5', 0.10, 0.30,
        'CADERNO-001', 'https://drive.google.com/uc?export=view&id=1WFbmLk-VFJJ0uYa8W5KdRC20gGGEXTSx', true, true, 1,
        1, '1OosCxJEq0zdIUuuzpNhzluX72qRldmRx'),
       ('Agenda Semanal', 39.90, 'Agenda personalizada com divisões semanais.', 'A5', 0.15, 0.25, 'AGENDA-001',
        'url/imagem/agenda_semanal.jpg', true, false, 1, 2, '1OosCxJEq'),
       ('Topo de Bolo Personalizado', 49.90, 'Topo de bolo com nome e data do evento.', '30cm', 0.20, 0.35, 'TOPO-001',
        'url/imagem/topo_bolo_personalizado.jpg', true, true, 2, 3, '1OosCxJEq'),
       ('Topo de Bolo Casamento', 69.90, 'Topo de bolo elegante para casamentos.', '30cm', 0.25, 0.40, 'TOPO-002',
        'url/imagem/topo_bolo_casamento.jpg', true, true, 2, 4, '1OosCxJEq'),
       ('Balão de Festa', 9.90, 'Balão de festa de 30cm, disponível em várias cores.', '30cm', 0.05, 0.10, 'BALAO-001',
        'url/imagem/balao_festa.jpg', false, false, 3, 5, '1OosCxJEq'),
       ('Faixa Personalizada', 19.90, 'Faixa personalizada com mensagem para festas.', '2m', 0.10, 0.20, 'FAIXA-001',
        'url/imagem/faixa_personalizada.jpg', true, false, 3, 6, '1OosCxJEq');

INSERT INTO imagens_produto (url_img_adicional, fk_produto, id_img_drive)
VALUES ('https://drive.google.com/uc?export=view&id=1DqrBxh7YyKSdbCNVPExhxdGLZFJR-xSH', 1,
        '1kJUI8FDa3Z4qVDxRvS0wYzeZwGrt55r2'),
       ('https://drive.google.com/uc?export=view&id=1DqrBxh7YyKSdbCNVPExhxdGLZFJR-xSH', 1,
        '1kJUI8FDa3Z4qVDxRvS0wYzeZwGrt55r2'),
       ('url/imagem/adicional_agenda.jpg', 2, 'abc123'),
       ('url/imagem/adicional_topo_bolo.jpg', 3, 'abc123'),
       ('url/imagem/adicional_topo_bolo_casamento.jpg', 4, 'abc123'),
       ('url/imagem/adicional_balao.jpg', 5, 'abc123'),
       ('url/imagem/adicional_faixa.jpg', 6, 'abc123');

INSERT INTO personalizacao (nome_personalizacao, tipo_personalizacao, fk_produto)
VALUES ('Personalização de Capa', 'Texto', 1),
       ('Personalização de Datas', 'Texto', 2),
       ('Design Especial para Casamento', 'Design', 4),
       ('Mensagem Especial', 'Texto', 3),
       ('Mensagem para Faixa', 'Texto', 6);

INSERT INTO opcao_personalizacao (nome_opcao, descricao, acrescimo_opcao, url_img_opcao, fk_personalizacao,
                                  id_img_drive)
VALUES ('Texto em Ouro', 'Texto na capa em efeito dourado', 5.00,
        'https://drive.google.com/uc?export=view&id=1JXubzQ5UKB_DMHWcLOI-5MFoqDBNRPvc', 1,
        '1cCAa5y637fsJ4VZ96Lqz5Utz_ZcZKo49'),
       ('Texto em Prata', 'Texto na capa em efeito prateado', 4.00,
        'https://drive.google.com/uc?export=view&id=1XXV-Pbr_gQ9SbBK1WOA6IEPictR14Ik-', 1,
        '1OLxbmeet0tTxCn5BOIas0LmB7Y4G7pbf'),
       ('Data em Dourado', 'Datas em efeito dourado', 3.00, 'url/imagem/data_dourada.jpg', 3, 'abc123'),
       ('Data em Prata', 'Datas em efeito prateado', 2.00, 'url/imagem/data_prateada.jpg', 3, 'abc123'),
       ('Design Floral', 'Design floral para casamentos', 8.00, 'url/imagem/design_floral.jpg', 4, 'abc123'),
       ('Design Minimalista', 'Design minimalista para casamentos', 6.00, 'url/imagem/design_minimalista.jpg', 4,
        'abc123'),
       ('Mensagem em Dourado', 'Mensagem em efeito dourado', 4.00, 'url/imagem/mensagem_dourada.jpg', 5, 'abc123'),
       ('Mensagem em Prata', 'Mensagem em efeito prateado', 3.00, 'url/imagem/mensagem_prateada.jpg', 5, 'abc123'),
       ('Mensagem em Vermelho', 'Mensagem em efeito vermelho', 2.00, 'url/imagem/mensagem_vermelha.jpg', 5, 'abc123'),
       ('Mensagem em Azul', 'Mensagem em efeito azul', 2.00, 'url/imagem/mensagem_azul.jpg', 5, 'abc123'),
       ('Mensagem em Verde', 'Mensagem em efeito verde', 2.00, 'url/imagem/mensagem_verde.jpg', 5, 'abc123'),
       ('Mensagem em Amarelo', 'Mensagem em efeito amarelo', 2.00, 'url/imagem/mensagem_amarela.jpg', 5, 'abc123'),
       ('Mensagem em Rosa', 'Mensagem em efeito rosa', 2.00, 'url/imagem/m', 5, 'abc123');

INSERT INTO material_produto (fk_material, fk_produto, qtd_material_necessario)
VALUES (1, 1, 2),
       (2, 1, 1),
       (1, 2, 3),
       (2, 2, 1),
       (1, 3, 1),
       (2, 3, 1),
       (3, 4, 1),
       (4, 5, 5),
       (1, 6, 2);

INSERT INTO USUARIO
(NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO, CARGO_USUARIO, TELEFONE_USUARIO, STATUS_USUARIO, DATA_CADASTRO_USUARIO,
 DATA_ATUALIZACAO_USUARIO, CPF_USUARIO, GENERO_USUARIO, URL_IMG_USUARIO, DATA_NASCIMENTO_USUARIO, ID_GOOGLE)
VALUES ('Cláudio Araújo', 'claudio@gmail.com', '$2b$12$4FM3A0un93R72ieiEddIE.J9hWbrO64j93W4cJZy0jyQcQo2WMFBC', 'ADMIN',
        '(11) 98765-4321', 'HABILITADO',
        NOW(), NOW(), '123.456.789-09', 1, 'http://img.png', '2005-01-07', NULL);

